<a href="https://colab.research.google.com/github/olatnattantalo/colabdeeplearning/blob/master/notebooks/Deep_Learning_com_Google_Colab_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
torch.cuda.is_available()

True

In [0]:
device = torch.device('cuda')
print(device)

cuda


In [0]:
torch.rand(3, 3)

tensor([[0.2241, 0.1207, 0.4927],
        [0.0066, 0.4226, 0.4362],
        [0.7747, 0.4345, 0.1190]])

In [0]:
b = torch.rand(3, 3).to(device) 

In [0]:
print(b)

tensor([[0.3960, 0.8370, 0.7597],
        [0.7644, 0.2984, 0.0179],
        [0.9854, 0.8884, 0.5772]], device='cuda:0')


In [0]:
c = torch.rand(3, 3).cuda()
c

tensor([[0.6959, 0.2784, 0.6864],
        [0.4959, 0.6705, 0.1636],
        [0.2874, 0.3595, 0.1463]], device='cuda:0')

In [0]:
import time

start = time.time()
a = torch.ones(400, 400)
for _ in range(10000):
    a += a
duration = time.time() - start
print(f'CPU time: {duration}')

print("----------------------")

start = time.time()
b = torch.ones(400, 400).to(device)
for _ in range(10000):
    b += b
duration = time.time() - start
print(f'GPU time: {duration}')

CPU time: 0.1978588104248047
----------------------
GPU time: 0.07151651382446289


In [0]:
# memory footprint support libraries/code
!ln -sf /opt/bin/nvidia-smi /usr/bin/nvidia-smi
!pip install gputil
!pip install psutil
!pip install humanize
import psutil
import humanize
import os
import GPUtil as GPU
GPUs = GPU.getGPUs()
# XXX: only one GPU on Colab and isn’t guaranteed
gpu = GPUs[0]
def printm():
    process = psutil.Process(os.getpid())
    print("Gen RAM Free: " + humanize.naturalsize( psutil.virtual_memory().available ), " | Proc size: " + humanize.naturalsize( process.memory_info().rss))
    print("GPU RAM Free: {0:.0f}MB | Used: {1:.0f}MB | Util {2:3.0f}% | Total {3:.0f}MB".format(gpu.memoryFree, gpu.memoryUsed, gpu.memoryUtil*100, gpu.memoryTotal))
printm()

Gen RAM Free: 11.2 GB  | Proc size: 2.5 GB
GPU RAM Free: 15563MB | Used: 717MB | Util   4% | Total 16280MB
