<a href="https://colab.research.google.com/github/olatnattantalo/colabdeeplearning/blob/master/notebooks/Deep_Learning_com_Google_Colab_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [0]:
y = torch.tensor([
    [2, 3, 4],
    [5, 6, 7],
    [9, 4, 5]
])
y

tensor([[2, 3, 4],
        [5, 6, 7],
        [9, 4, 5]])

In [0]:
y = torch.tensor([
    [2, 3, 4],
    [5, 6, 7],
    [9, 4, 5]
], dtype=torch.float)
y

tensor([[2., 3., 4.],
        [5., 6., 7.],
        [9., 4., 5.]])

In [0]:
torch.ones(1, 3, dtype=torch.int)

tensor([[1, 1, 1]], dtype=torch.int32)

In [0]:
torch.zeros(3, 5, 6, dtype=torch.float)

tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]])

In [0]:
z = torch.rand(3, 6, 4, dtype=torch.float)
z

tensor([[[0.1758, 0.2281, 0.4236, 0.8793],
         [0.7200, 0.5605, 0.8970, 0.7165],
         [0.5325, 0.1454, 0.6946, 0.5141],
         [0.7788, 0.8321, 0.5686, 0.6277],
         [0.4132, 0.1475, 0.5982, 0.6447],
         [0.1418, 0.9138, 0.9585, 0.0736]],

        [[0.1893, 0.9223, 0.8233, 0.0360],
         [0.3979, 0.8877, 0.8784, 0.6291],
         [0.7715, 0.0753, 0.3255, 0.0027],
         [0.2769, 0.4615, 0.2357, 0.3136],
         [0.7649, 0.9247, 0.6387, 0.6298],
         [0.7650, 0.8029, 0.6446, 0.2405]],

        [[0.3312, 0.4323, 0.7742, 0.4266],
         [0.2747, 0.0890, 0.5353, 0.1521],
         [0.4740, 0.3612, 0.1902, 0.2432],
         [0.7513, 0.4276, 0.8316, 0.1848],
         [0.2167, 0.4922, 0.7055, 0.3975],
         [0.0668, 0.7475, 0.6464, 0.3697]]])

In [0]:
print(y)
y[0]

tensor([[2., 3., 4.],
        [5., 6., 7.],
        [9., 4., 5.]])


tensor([2., 3., 4.])

In [0]:
y[:, 1]

tensor([3., 6., 4.])

In [0]:
z[2, :, 0]

tensor([0.3312, 0.2747, 0.4740, 0.7513, 0.2167, 0.0668])

In [0]:
y.size()

torch.Size([3, 3])

In [0]:
y.size()[0]

3

In [0]:
t = torch.rand(3, 3)
t

tensor([[0.5535, 0.7661, 0.9992],
        [0.6827, 0.2899, 0.0535],
        [0.3584, 0.6536, 0.2869]])

In [0]:
y + t

tensor([[2.5535, 3.7661, 4.9992],
        [5.6827, 6.2899, 7.0535],
        [9.3584, 4.6536, 5.2869]])

In [0]:
y * t

tensor([[1.1070, 2.2984, 3.9967],
        [3.4136, 1.7392, 0.3744],
        [3.2252, 2.6143, 1.4347]])

In [0]:
y * 3

tensor([[ 6.,  9., 12.],
        [15., 18., 21.],
        [27., 12., 15.]])

In [0]:
print(y)

tensor([[2., 3., 4.],
        [5., 6., 7.],
        [9., 4., 5.]])


In [0]:
y.reshape(1, 9)

tensor([[2., 3., 4., 5., 6., 7., 9., 4., 5.]])

In [0]:
y.reshape(-1,)

tensor([2., 3., 4., 5., 6., 7., 9., 4., 5.])

In [0]:
torch.squeeze(y.reshape(1, 9))

tensor([2., 3., 4., 5., 6., 7., 9., 4., 5.])

In [0]:
y.sum()

tensor(45.)

In [0]:
y.sum(0)

tensor([16., 13., 16.])

In [0]:
torch.max(y)

tensor(9.)

In [0]:
print(y)

tensor([[2., 3., 4.],
        [5., 6., 7.],
        [9., 4., 5.]])


In [0]:
values, indices = torch.max(y, 0)
print(values)
print(indices)

tensor([9., 6., 7.])
tensor([2, 1, 1])


In [0]:
y[0, 0].item()

2.0

In [0]:
y[0, 0].item() == 1

False

In [0]:
y[0, 0] == 2

tensor(True)

In [0]:
y.numpy()

array([[2., 3., 4.],
       [5., 6., 7.],
       [9., 4., 5.]], dtype=float32)

In [0]:
import numpy as np

a = np.array([[2, 5], [6, 4]])
b = torch.from_numpy(a)
print(b)

tensor([[2, 5],
        [6, 4]])


In [0]:
a[0, 0] = 2
a

array([[2, 5],
       [6, 4]])

In [0]:
b

tensor([[2, 5],
        [6, 4]])